version: '3'

services:
  # SvelteKit app
  svelte-app:
    image: node:alpine
    working_dir: /app
    volumes:
      - .:/app:Z
    command: sh -c "npm install && npm run dev "
    ports:
      - "5173:5173"
    depends_on:
      - postgres

  # PostgreSQL database
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_database_user
      POSTGRES_PASSWORD: your_database_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:Z

volumes:
  pgdata:

